/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fuzzy;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author FadelTrivandi
 */
public class Frame extends javax.swing.JFrame {

    /**
     * Creates new form Frame
     */
    public Frame() {
        initComponents();
        String pathRule = textFieldRule.getText(), pathVariabel = textFieldVariable.getText();
        OperasiFile file = new OperasiFile();
        modelTabelRule = new DefaultTableModel(file.inputRule(pathRule), file.getColumnNames(pathRule));
        tabel.setModel(modelTabelRule);
        Variabel[] var = file.getVariabel(pathVariabel);
        for (Variabel var1 : var) {
            String varTitle = var1.getName();
            variabelComboBox.addItem(varTitle);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        panelTab = new javax.swing.JTabbedPane();
        panelSettings = new javax.swing.JPanel();
        labelVariabel = new javax.swing.JLabel();
        ruleVariabel = new javax.swing.JLabel();
        textFieldVariable = new javax.swing.JTextField();
        textFieldRule = new javax.swing.JTextField();
        variableFileChooser = new javax.swing.JButton();
        ruleFileChooser = new javax.swing.JButton();
        ruleTab = new javax.swing.JTabbedPane();
        tabelScroll = new javax.swing.JScrollPane();
        tabel = new javax.swing.JTable();
        graphic = new javax.swing.JPanel();
        variabelComboBox = new javax.swing.JComboBox();
        buttonGraphic = new javax.swing.JButton();
        panelChart = new javax.swing.JPanel();
        copyrightSetting = new javax.swing.JLabel();
        labelJudul = new javax.swing.JLabel();
        tombolLoad = new javax.swing.JButton();
        panelInput = new javax.swing.JPanel();
        panelInputEsKrim = new javax.swing.JPanel();
        labelVariable1 = new javax.swing.JLabel();
        variabel1 = new javax.swing.JTextField();
        labelVariable2 = new javax.swing.JLabel();
        variabel2 = new javax.swing.JTextField();
        tombolHitung = new javax.swing.JButton();
        tombolReset = new javax.swing.JButton();
        scrollPaneTabelHasil = new javax.swing.JScrollPane();
        tabelHasil = new javax.swing.JTable();
        labelHasil = new javax.swing.JLabel();
        hasil = new javax.swing.JTextField();
        gambarEsKrim = new javax.swing.JLabel();
        copyright = new javax.swing.JLabel();
        titleLabel = new javax.swing.JLabel();
        panelAbout = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        panelHelp = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();

        fileChooser.setAcceptAllFileFilterUsed(false);
        fileChooser.setCurrentDirectory(new java.io.File("D:\\Java\\NetBeansProjects\\Fuzzy"));
        fileChooser.setDialogTitle("");
        fileChooser.setToolTipText("");
        fileChooser.addChoosableFileFilter(new FileNameExtensionFilter("Text Files", "txt"));
        fileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fileChooserActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelVariabel.setText("Variable (Input & Output)");

        ruleVariabel.setText("Rule");

        textFieldVariable.setEditable(false);
        textFieldVariable.setText("Member.txt");

        textFieldRule.setEditable(false);
        textFieldRule.setText("Rule.txt");

        variableFileChooser.setText("Browse");
        variableFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                variableFileChooserActionPerformed(evt);
            }
        });

        ruleFileChooser.setText("Browse");
        ruleFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ruleFileChooserActionPerformed(evt);
            }
        });

        tabel.setToolTipText("");
        tabelScroll.setViewportView(tabel);

        ruleTab.addTab("Rule", tabelScroll);

        buttonGraphic.setText("View");
        buttonGraphic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGraphicActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelChartLayout = new javax.swing.GroupLayout(panelChart);
        panelChart.setLayout(panelChartLayout);
        panelChartLayout.setHorizontalGroup(
            panelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelChartLayout.setVerticalGroup(
            panelChartLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 213, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout graphicLayout = new javax.swing.GroupLayout(graphic);
        graphic.setLayout(graphicLayout);
        graphicLayout.setHorizontalGroup(
            graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicLayout.createSequentialGroup()
                .addComponent(variabelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonGraphic)
                .addGap(0, 441, Short.MAX_VALUE))
            .addGroup(graphicLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        graphicLayout.setVerticalGroup(
            graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(graphicLayout.createSequentialGroup()
                .addGroup(graphicLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(variabelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonGraphic))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelChart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        ruleTab.addTab("Graphic", graphic);

        copyrightSetting.setText("copyright @fadeltd, @indraarrohmah, @anz_drowz, @ngengs, @dy_Nin 2014");

        labelJudul.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        labelJudul.setText("PREDIKSI PERMINTAAN ES KRIM METODE TSUKAMOTO");

        tombolLoad.setText("Load");
        tombolLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolLoadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSettingsLayout = new javax.swing.GroupLayout(panelSettings);
        panelSettings.setLayout(panelSettingsLayout);
        panelSettingsLayout.setHorizontalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelSettingsLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(labelJudul))
                    .addGroup(panelSettingsLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ruleTab)
                            .addGroup(panelSettingsLayout.createSequentialGroup()
                                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelVariabel)
                                    .addComponent(ruleVariabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldVariable, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(textFieldRule))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ruleFileChooser, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(variableFileChooser, javax.swing.GroupLayout.Alignment.TRAILING)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelSettingsLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(copyrightSetting)))
                .addContainerGap())
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(tombolLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelSettingsLayout.setVerticalGroup(
            panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSettingsLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVariabel)
                    .addComponent(textFieldVariable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(variableFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ruleVariabel)
                    .addComponent(textFieldRule, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ruleFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tombolLoad)
                .addGap(1, 1, 1)
                .addComponent(ruleTab, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyrightSetting)
                .addContainerGap())
        );

        panelTab.addTab("Setting", panelSettings);

        panelInputEsKrim.setBorder(javax.swing.BorderFactory.createTitledBorder("Input Prediksi Permintaan Es Krim"));

        labelVariable1.setText("Suhu (dalam Celcius) :");

        labelVariable2.setText("Orang yang berlibur :");

        tombolHitung.setText("Prediksi");
        tombolHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolHitungActionPerformed(evt);
            }
        });

        tombolReset.setText("Reset");
        tombolReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tombolResetActionPerformed(evt);
            }
        });

        scrollPaneTabelHasil.setViewportView(tabelHasil);

        labelHasil.setText("Hasil Prediksi :");

        hasil.setEditable(false);

        javax.swing.GroupLayout panelInputEsKrimLayout = new javax.swing.GroupLayout(panelInputEsKrim);
        panelInputEsKrim.setLayout(panelInputEsKrimLayout);
        panelInputEsKrimLayout.setHorizontalGroup(
            panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputEsKrimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputEsKrimLayout.createSequentialGroup()
                        .addComponent(labelHasil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelInputEsKrimLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(tombolHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tombolReset))
                    .addComponent(scrollPaneTabelHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panelInputEsKrimLayout.createSequentialGroup()
                        .addGroup(panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputEsKrimLayout.createSequentialGroup()
                                .addComponent(labelVariable1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(panelInputEsKrimLayout.createSequentialGroup()
                                .addComponent(labelVariable2)
                                .addGap(7, 7, 7)))
                        .addGroup(panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(variabel1)
                            .addComponent(variabel2))))
                .addContainerGap())
        );
        panelInputEsKrimLayout.setVerticalGroup(
            panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputEsKrimLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVariable1)
                    .addComponent(variabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelVariable2)
                    .addComponent(variabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tombolHitung)
                    .addComponent(tombolReset))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPaneTabelHasil, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputEsKrimLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelHasil)
                    .addComponent(hasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        gambarEsKrim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/esKrim.png"))); // NOI18N

        copyright.setText("copyright @fadeltd, @indraarrohmah, @anz_drowz, @ngengs, @dy_Nin 2014");

        titleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        titleLabel.setText("PREDIKSI PERMINTAAN ES KRIM METODE TSUKAMOTO");

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(titleLabel)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(copyright)
                .addGap(19, 19, 19))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(gambarEsKrim)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelInputEsKrim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gambarEsKrim, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelInputEsKrim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(copyright, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        panelTab.addTab("Input", panelInput);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("PREDIKSI PERMINTAAN ES KRIM METODE TSUKAMOTO");

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel2.setText("disusun untuk memenuhi tugas akhir");

        jLabel3.setText("Informatika / Ilmu Komputer Universitas Brawijaya");

        jLabel4.setText("Disusun oleh");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel5.setText("Andro Subagio | 115090600111007");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel6.setText("Fadel Trivandi Dipantara | 115090607111027");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel7.setText("Indrahidayati Nur R. |115090607111013");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel8.setText("Nindy Akvalentin K. |115060807111057");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel9.setText("Rizky Kharisma | 115090600111027");

        javax.swing.GroupLayout panelAboutLayout = new javax.swing.GroupLayout(panelAbout);
        panelAbout.setLayout(panelAboutLayout);
        panelAboutLayout.setHorizontalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel3))
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jLabel1))
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel4))
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addComponent(jLabel5))
                    .addGroup(panelAboutLayout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelAboutLayout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jLabel2))
                            .addGroup(panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel9)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAboutLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(100, 100, 100)))
                .addContainerGap(95, Short.MAX_VALUE))
        );
        panelAboutLayout.setVerticalGroup(
            panelAboutLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAboutLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(13, 13, 13)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        panelTab.addTab("About", panelAbout);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("PREDIKSI PERMINTAAN ES KRIM METODE TSUKAMOTO");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Menu Setting");

        jLabel12.setText("Variabel input & output untuk menentukan fungsi keanggotaan. File yang dimasukkan dalam bentuk *.txt.");

        jLabel13.setText("Rule untuk menentukan aturan yang digunakan dalam perhitungan. File yang dimasukkan dalam bentuk *.txt.");

        jLabel14.setText("Tombol Load untuk memproses inputan file (variabel dan rule).");

        jLabel15.setText("Jika berhasil, maka rule yang dimasukkan akan muncul ke dalam kolom Rule.");

        jLabel16.setText("Tab Graphic untuk menampilkan grafik dari permintaan.");

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel17.setText("Menu Input");

        jLabel18.setText("Inputan suhu berupa angka bertipe double (dengan koma) dalam satuan celcius.");

        jLabel19.setText("Orang berlibur berupa angka bertipe double (dengan koma) dalam persen.");

        jLabel20.setText("Tombol Prediksi untuk menghitung inputan. Hasilnya akan ditampilkan dalam kolom yang disediakan.");

        jLabel21.setText("Tombol Reset untuk mengosongkan inputan Suhu dan Orang yang berlibur.");

        javax.swing.GroupLayout panelHelpLayout = new javax.swing.GroupLayout(panelHelp);
        panelHelp.setLayout(panelHelpLayout);
        panelHelpLayout.setHorizontalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addGroup(panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHelpLayout.createSequentialGroup()
                        .addGroup(panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelHelpLayout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jLabel10))
                            .addGroup(panelHelpLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(panelHelpLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel15)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel18)
                                            .addComponent(jLabel19)
                                            .addComponent(jLabel20)
                                            .addComponent(jLabel21)))
                                    .addComponent(jLabel17))))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHelpLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel13)))
                .addContainerGap())
        );
        panelHelpLayout.setVerticalGroup(
            panelHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap(173, Short.MAX_VALUE))
        );

        panelTab.addTab("Help", panelHelp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTab)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void variableFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_variableFileChooserActionPerformed
        fileChooser.showOpenDialog(tabel);
        fileChooser.setDialogTitle("File Variabel");
        if (String.valueOf(fileChooser.getSelectedFile()) != null) {
            textFieldVariable.setText(String.valueOf(fileChooser.getSelectedFile()));
        } else {
            textFieldVariable.setText("");
        }
        System.out.println(fileChooser.getDialogTitle());
        //textFieldVariable.setText(String.valueOf(fileChooser.getCurrentDirectory()));
    }//GEN-LAST:event_variableFileChooserActionPerformed

    private void ruleFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ruleFileChooserActionPerformed
        fileChooser.showOpenDialog(tabel);
        fileChooser.setDialogTitle("File Rule");
        if (String.valueOf(fileChooser.getSelectedFile()) != null) {
            textFieldRule.setText(String.valueOf(fileChooser.getSelectedFile()));
        } else {
            textFieldVariable.setText("");
        }
        System.out.println(fileChooser.getDialogTitle());
    }//GEN-LAST:event_ruleFileChooserActionPerformed

    private void tombolResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolResetActionPerformed
        variabel1.setText("");
        variabel2.setText("");
        tabelHasil.hide();
        hasil.setText("");
    }//GEN-LAST:event_tombolResetActionPerformed

    private void tombolHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolHitungActionPerformed
        try {
            double[] var = new double[2];
            var[0] = Double.parseDouble(variabel1.getText());
            var[1] = Double.parseDouble(variabel2.getText());

            if (var[0] > 45) {
                JOptionPane.showMessageDialog(panelAbout, "Suhu lebih dari 45 derajat Celcius");
            } else {
                OperasiFile file = new OperasiFile();
                String pathRule = textFieldRule.getText(), pathVariabel = textFieldVariable.getText();;
                ArrayList<String> columnNames = new ArrayList();
                String[] getColumn = file.getColumnNames(pathRule);
                String[] columnFormula = {"α predikat", "z", "α predikat * z"};
                columnNames.addAll(Arrays.asList(getColumn));
                columnNames.addAll(Arrays.asList(columnFormula));
                String[] column = new String[columnNames.size()];
                for (int i = 0; i < column.length; i++) {
                    column[i] = columnNames.get(i);
                }

                String[][] tableContent = file.inputVariabel(pathVariabel, pathRule, var);
                modelTabelHasil = new DefaultTableModel(tableContent, column);
                tabelHasil.setModel(modelTabelHasil);
                tabelHasil.show();
            //System.out.println(file.inputVariabel(pathVariabel, pathRule, var).length);

                double sumAlphaZ = 0, sumAlpha = 0;
                for (int i = 0; i < file.inputVariabel(pathVariabel, pathRule, var).length; i++) {
                    sumAlpha += Double.valueOf(tableContent[i][tableContent[i].length - 3]);
                    sumAlphaZ += Double.valueOf(tableContent[i][tableContent[i].length - 1]);
                }
                double prediksi = sumAlphaZ / sumAlpha;
                hasil.setText(String.valueOf(prediksi));
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(panelInput, "Data masih kosong");
        }
    }//GEN-LAST:event_tombolHitungActionPerformed

    private void tombolLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tombolLoadActionPerformed
        OperasiFile file = new OperasiFile();
        String pathRule = textFieldRule.getText();//, pathVariabel = textFieldVariable.getText();
        //file.inputVariabel(pathVariabel);
        //file.inputRule(pathRule);
        modelTabelRule = new DefaultTableModel(file.inputRule(pathRule), file.getColumnNames(pathRule));
        tabel.setModel(modelTabelRule);
        //tabel

    }//GEN-LAST:event_tombolLoadActionPerformed

    private void fileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fileChooserActionPerformed

    }//GEN-LAST:event_fileChooserActionPerformed

    private void buttonGraphicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGraphicActionPerformed
        OperasiFile file = new OperasiFile();
        String pathVariabel = textFieldVariable.getText();
        Variabel[] var = file.getVariabel(pathVariabel);

        LineChart demo = new LineChart(String.valueOf(variabelComboBox.getSelectedItem()), var[variabelComboBox.getSelectedIndex()]);
        demo.pack();
        demo.setVisible(true);
        RefineryUtilities.centerFrameOnScreen(demo);
//        pane = new JPanel();
//        pane = demo.createDemoPanel(String.valueOf(variabelComboBox.getSelectedItem()));
//        panelChart.add(pane);
    }//GEN-LAST:event_buttonGraphicActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonGraphic;
    private javax.swing.JLabel copyright;
    private javax.swing.JLabel copyrightSetting;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel gambarEsKrim;
    private javax.swing.JPanel graphic;
    private javax.swing.JTextField hasil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelHasil;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelVariabel;
    private javax.swing.JLabel labelVariable1;
    private javax.swing.JLabel labelVariable2;
    private javax.swing.JPanel panelAbout;
    private javax.swing.JPanel panelChart;
    private javax.swing.JPanel panelHelp;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPanel panelInputEsKrim;
    private javax.swing.JPanel panelSettings;
    private javax.swing.JTabbedPane panelTab;
    private javax.swing.JButton ruleFileChooser;
    private javax.swing.JTabbedPane ruleTab;
    private javax.swing.JLabel ruleVariabel;
    private javax.swing.JScrollPane scrollPaneTabelHasil;
    private javax.swing.JTable tabel;
    private javax.swing.JTable tabelHasil;
    private javax.swing.JScrollPane tabelScroll;
    private javax.swing.JTextField textFieldRule;
    private javax.swing.JTextField textFieldVariable;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JButton tombolHitung;
    private javax.swing.JButton tombolLoad;
    private javax.swing.JButton tombolReset;
    private javax.swing.JTextField variabel1;
    private javax.swing.JTextField variabel2;
    private javax.swing.JComboBox variabelComboBox;
    private javax.swing.JButton variableFileChooser;
    // End of variables declaration//GEN-END:variables
    private javax.swing.table.DefaultTableModel modelTabelRule;
    private javax.swing.table.DefaultTableModel modelTabelHasil;
    //private javax.swing.JPanel pane;
}
